name: extract

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of uosserver image to extract'
        type: string
        required: true

jobs:
  # ╔═════════════════════════════════════════════════════╗
  # ║                                                     ║
  # ║                                                     ║
  # ║                    EXTRACT IMAGE                    ║
  # ║                                                     ║
  # ║                                                     ║
  # ╚═════════════════════════════════════════════════════╝
  extract:
    name: create container image
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      # ╔═════════════════════════════════════════════════════╗
      # ║             CONTAINER REGISTRY LOGIN                ║
      # ╚═════════════════════════════════════════════════════╝
      # DOCKER HUB
      - name: docker / login to hub
        uses: redhat-actions/podman-login@de1fa16e0ecaaa44c0d537db88f68d183b32a8e0
        with:
          registry: docker.io
          username: 11notes
          password: ${{ secrets.DOCKER_TOKEN }}

      # GITHUB CONTAINER REGISTRY
      - name: github / login to ghcr
        uses: redhat-actions/podman-login@de1fa16e0ecaaa44c0d537db88f68d183b32a8e0
        with:
          registry: ghcr.io
          username: 11notes
          password: ${{ secrets.GITHUB_TOKEN }}

      # REDHAT QUAY
      - name: quay / login to quay
        uses: redhat-actions/podman-login@de1fa16e0ecaaa44c0d537db88f68d183b32a8e0
        with:
          registry: quay.io
          username: 11notes+github
          password: ${{ secrets.QUAY_TOKEN }}


      # ╔═════════════════════════════════════════════════════╗
      # ║                 EXTRACT CONTAINER                   ║
      # ╚═════════════════════════════════════════════════════╝
      # REQUIREMENTS
      - name: requirements
        run: |
          mkdir -p ${HOME}/.config/containers
          chmod 755 ${HOME} ${HOME}/.config ${HOME}/.config/containers
          touch ${HOME}/.config/containers/storage.conf
          chmod 755 ${HOME}/.config/containers/storage.conf
          mkdir -p ${HOME}/.local/share/containers/storage/overlay
          mkdir -p ${HOME}/.local/share/containers/storage/overlay-images
          mkdir -p ${HOME}/.local/share/containers/storage/overlay-layers
          ARCH=$(arch)
          case "${ARCH}" in
            "x86_64")
              echo "DOWNLOAD_ARCH=x64" >> "${GITHUB_ENV}"
              echo "WORKFLOW_RUNNER_ARCH=amd64" >> "${GITHUB_ENV}"
            ;;
            "aarch64")
              echo "DOWNLOAD_ARCH=arm64" >> "${GITHUB_ENV}"
              echo "WORKFLOW_RUNNER_ARCH=arm64" >> "${GITHUB_ENV}"
          esac

      # DOWNLOAD
      - name: download
        run: |
          wget -q --show-progress --progress=bar:force -O /tmp/uosserver $(curl -s "https://fw-update.ubnt.com/api/firmware?filter=eq~~product~~unifi-os-server&filter=eq~~platform~~linux-${{ env.DOWNLOAD_ARCH }}&filter=eq~~channel~~release&sort=-version" | jq -r "._embedded.firmware[] | select(.version | test(\"v${{ github.event.inputs.version }}\")) | ._links.data.href")
          chmod +x /tmp/uosserver

      # INSTALL
      - name: install
        run: |
          echo "y" | sudo /tmp/uosserver || echo "timeout reached, extracting container image"
          sudo cp -a /home/uosserver/.local/share/containers/storage/overlay/. ${HOME}/.local/share/containers/storage/overlay/
          sudo cp -a /home/uosserver/.local/share/containers/storage/overlay-images/. ${HOME}/.local/share/containers/storage/overlay-images/
          sudo cp -a /home/uosserver/.local/share/containers/storage/overlay-layers/. ${HOME}/.local/share/containers/storage/overlay-layers/
          sudo chown -R runner:runner ${HOME}/.local/share/containers/storage

      # EXTRACT
      - name: extract
        run: |
          IMAGE="localhost:5000/11notes/uosserver:fw-${{ github.event.inputs.version }}-${{ env.WORKFLOW_RUNNER_ARCH }}"
          echo "WORKFLOW_IMAGE=${IMAGE}" >> "${GITHUB_ENV}"
          podman push --tls-verify=false $(podman images uosserver --noheading | awk '{print $3}') ${IMAGE}

      # SCAN
      - name: scan with grype
        id: grype
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          image: ${{ env.WORKFLOW_IMAGE }}
          fail-build: true
          severity-cutoff: 'critical'
          output-format: 'sarif'
          by-cve: true
          cache-db: true

      # SCAN FAIL
      - name: scan with grype FAILED
        if: failure() || steps.grype.outcome == 'failure'
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          image: ${{ env.WORKFLOW_IMAGE }}
          fail-build: false
          severity-cutoff: 'critical'
          output-format: 'table'
          by-cve: true
          cache-db: true