name: extract-network

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  PASSWORD: "DsFR.DAmE.3eE7.7TMp"

on:
  workflow_dispatch:

jobs:
  # ╔═════════════════════════════════════════════════════╗
  # ║                                                     ║
  # ║                                                     ║
  # ║                    EXTRACT IMAGE                    ║
  # ║                                                     ║
  # ║                                                     ║
  # ╚═════════════════════════════════════════════════════╝
  extract:
    name: create container image
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      packages: write

    steps:
      # ╔═════════════════════════════════════════════════════╗
      # ║             EXTRACT APP FROM CONTAINER              ║
      # ╚═════════════════════════════════════════════════════╝
      # CHECKOUT ALL DEPTHS (ALL TAGS)
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: master
          fetch-depth: 0

      # RUN CONTAINER
      - name: run
        run: |
          mkdir -p ${{ runner.temp }}/network
          cd ./build/extract/network
          RUNNER_TMP=${{ runner.temp }}/network docker compose up -d

      # WAIT TILL CONTAINER STATUS IS HEALTHY
      - name: wait for startup
        run: |
          echo "checking container startup ..."
          RUN=1
          while [ ${RUN} -ge 1 ]; do
            HEALTH=$(docker inspect --format='{{json .State.Health}}' unifi-os-server-1 | jq -r '.Status')
            echo "container health: ${HEALTH}"
            if [ ${HEALTH} == "healthy" ]; then
              RUN=0
            else
              sleep 5s
            fi
          done

      # WAIT TILL UNIFI OS SERVER SETUP IS READY
      - name: wait for startup
        run: |
          echo "checking Unifi OS Server ready ..."
          RUN=1
          while [ ${RUN} -ge 1 ]; do
            STATUS=$(curl -skI -o /dev/null -w "%{http_code}" https://localhost/api/system/previous-subnet)
            echo "Unifi OS Server status: ${STATUS}"
            if [ ${STATUS} == 200 ]; then
              RUN=0
            else
              sleep 5s
            fi
          done

      # SETUP UNIFI OS SERVER
      - name: setup
        run: |
          echo "setup controller"
          curl -k -X POST https://localhost/api/setup \
          -H "Content-Type: application/json" \
          -d '{
            "hostname": "github",
            "timezone": "Europe/Zurich",
            "username": "admin",
            "password": "${{ env.PASSWORD }}",
            "email": "",
            "enableRemoteAdmin": false,
            "analytics": false
          }'

          sleep 60s

      # UPGRADE CONTROLLER
      - name: upgrade
        run: |
          echo "NETWORK_VERSION=$(docker exec unifi-os-server-1 cat /usr/lib/unifi/data/db/version)" >> "${GITHUB_ENV}"
          echo "authenticate and get token"
          RESPONSE_HEADERS=$(curl -ks -D - -o /dev/null https://localhost/api/auth/login \
            -c cookies.txt \
            -H "Content-Type: application/json" \
            -d '{
              "username": "admin",
              "password": "${{ env.PASSWORD }}"
            }')
          CSRF_TOKEN=$(echo ${RESPONSE_HEADERS} | grep -o "x-csrf-token: .*" | awk -F ' ' '{print $2}' | tr -d '\r')
          curl -k -X POST https://localhost/api/controllers/checkUpdates \
            -b cookies.txt \
            -H "Content-Type: application/json" \
            -H "x-csrf-token: $CSRF_TOKEN" \
            -d '{}'
          sleep 15s
          curl -ks -X POST https://localhost/api/controllers/network/update \
            -b cookies.txt \
            -H "Content-Type: application/json" \
            -H "x-csrf-token: ${CSRF_TOKEN}" \
            -d '{}'

      # WAIT FOR UPGRADE COMPLETION
      - name: wait upgrade
        run: |
          RUN=1
          while [ ${RUN} -ge 1 ]; do
            VERSION=$(docker exec unifi-os-server-1 cat /usr/lib/unifi/data/db/version)
            echo "current version: ${VERSION} (pre-upgrade: ${{ env.NETWORK_VERSION }})"
            if [ ${VERSION} != ${{ env.NETWORK_VERSION }} ]; then
              echo "NETWORK_VERSION_UPDATE=${VERSION}" >> "${GITHUB_ENV}"
              RUN=0
            else
              sleep 5s
            fi
          done

      # EXTRACT VERSION
      - name: extract
        run: |
          docker exec unifi-os-server-1 mkdir -p /ext/UniFi
          docker exec unifi-os-server-1 cp -rL /usr/lib/unifi/bin /ext/UniFi/bin
          docker exec unifi-os-server-1 cp -rL /usr/lib/unifi/dl /ext/UniFi/dl
          docker exec unifi-os-server-1 cp -rL /usr/lib/unifi/lib /ext/UniFi/lib
          docker exec unifi-os-server-1 cp -rL /usr/lib/unifi/webapps /ext/UniFi/webapps
          cd ${{ runner.temp }}/network
          zip -r UniFi-${{ env.NETWORK_VERSION_UPDATE }}.zip UniFi
          rm -rf UniFi

      # PUSH ZIP TO R2
      - uses: ryand56/r2-upload-action@4f4bf1b8f0b132344cefe6f69d6b8c7f6117d665 # v1.4
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: pub-11notes-dev
          source-dir: ${{ runner.temp }}/network
          destination-dir: ./app/unifi-network-controller
          keep-file-fresh: true